vich_uploader:
    db_driver: orm

    mappings:
        actor_file:
           uri_prefix: /images/actors
           upload_destination: '%kernel.project_dir%/public/images/actors'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        poster_file:
           uri_prefix: /images/posters
           upload_destination: '%kernel.project_dir%/public/images/posters'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
